inovex/CalendarSync

docs/systemd-timers.md
related: https://github.com/inovex/CalendarSync/issues/26
=> docs: add systemd timer docs

internal/adapter/google/client.go, internal/adapter/google/event.go, internal/models/metadata.go, internal/sync/controller.go
This PR removes the (not really necessary) special case to clean up events with an emtpy (but existing) SourceID field in their ExtendedProperties, as suggested in #33.
The more important change is the introduction of a prefix for the metadata fields to prevent potential collisions. To ensure backwards compatibility, the code falls back to the old unprefixed keys if the prefixed keys do not exist. The idea here is to eventually drop support for the unprefixed keys, but support both to simplify the transition.
=> Prefix metadata in ExtendedProperties of GCal events

internal/adapter/outlook_http/client.go
Fix for the description mapping of the outlook adapter. Might need a deeper inspection concerning the content type und the general Content.
=> Fixed outlook description mapping

.github/workflows/build.yaml, .goreleaser.yaml, cmd/calendarsync/main.go
- feat: add version flag
- fix: github build workflow
- fix: add missing ldflags to goreleaser
=> feat: add version flag

internal/config/config.go, internal/config/config_test.go, testdata/mixed_auth_storage.yaml
Changed the validation mechanism to an initialised struct. 🚧
=> refactor: change the default configuration into a explicit structed

CONTRIBUTING.md, README.md, cmd/calendarsync/main.go, docs/systemd-timers.md
add warning and note to migrate to the env variable, as the flag will be removed in later versions
=> fix: deprecate the usage of the storage encryption key command line flag

.github/dependabot.yml, .github/workflows/build.yaml, .github/workflows/release.yaml, .goreleaser.yaml, README.md, cmd/calendarsync/main.go, docker-compose.yml, example.sync.yaml, internal/adapter/google/event.go, internal/adapter/outlook_http/client.go, internal/adapter/outlook_http/models.go, internal/config/config.go, internal/filter/allDayEvents.go, internal/filter/declinedEvents.go, internal/models/event.go, internal/sync/controller.go, internal/sync/controller_test.go, internal/sync/filter.go, internal/sync/transformer.go, internal/sync/util.go, testdata/testconfig.yaml
- fmt: make the linter happy and add document starts to yamls
- feat: add Accepted field to models.Event
- feat(outlook): add ResponseStatus field and map to models.Event.Accepted
- feat(google): check for Event Response and map to models.Event.Accepted
- feat: add sync_declined_events field to config
- feat: add SyncDeclinedEvents field to controller struct
- test: modify tests for the newly introduced accepted field and controller property
- feat: add function to remove declined events if config parameter is set
- docs: add sync_declined_fields parameter to readme.md
=> feat: Implement option to enable / disable sync of declined events

internal/sync/controller_test.go
Synchronizing an event now requires calling `GetCalendarID()` on the sink. This requirement was concurrently introduced by the commit
`feat: do not resurrect event when syncing in both directions` #67  which conflicts with `feat: Implement option to enable / disable sync of declined events` #62 .
=> Fix test failure

internal/auth/yaml_storage.go
=> Decrypt only once and hold calendar auth data in memory

example.sync.yaml, internal/filter/allDayEvents_test.go, internal/filter/declinedEvents_test.go, internal/filter/regexTitle.go, internal/filter/regexTitle_test.go, internal/filter/util.go, internal/filter/util_test.go, internal/sync/filter.go, internal/sync/transformer.go
- fix: better error handling in the transformerfactory
- fix: better error handling in the filterfactory
- fix: add new filter 'regexTitle'
- test: add test for 'regexTitle' filter
- test: add test for 'allDayEvents' filter
- test: add test for 'declinedEvents' filter
=> Add regexTitle Filter

docs/adapters.md, example.sync.yaml, internal/adapter/zep/client.go
- fix: zep needs to fulfill the configurable interface
- docs: update docs for the zep adapter
=> fix: ZEP Adapter

internal/adapter/zep/client.go
ZEP Events are mostly absences in the form of "Bezahlter Urlaub". Those events should always be accepted and should therefore not fall through the `DeclinedEvents` filter if configured.
=> ZEP Events are always accepted

README.md, example.sync.yaml, internal/filter/timeFrame.go, internal/filter/timeFrame_test.go, internal/sync/filter.go, internal/sync/util.go
related to https://github.com/inovex/CalendarSync/issues/114
- **fix: type conversion in autoConfigure function for integers**
- **feat: add timeFrame Filter**
- **feat: add timeFrame filter tests**
- **docs: update readme with the new filter**
- **docs: update example.sync.yaml with the new filter**
=> feat: Timeframe Filter

README.md, example.sync.yaml, internal/auth/yaml_storage.go
Allow the path to the auth storage to start with a tilde and expand it to the home directory of the user executing the program.
If it doesn't start with a tilde, the current behaviour is kept.
=> feat: do tilde expansion for yaml storage path

cmd/calendarsync/main.go, internal/adapter/google/adapter.go, internal/adapter/google/client.go, internal/adapter/outlook_http/adapter.go, internal/adapter/port/interface.go, internal/adapter/sink_adapter.go, internal/adapter/source_adapter.go, internal/adapter/zep/client.go
Sometimes i want to authenticate using an incognito window, but calendarsync opens the auth dialog in the last recent window i used. To make sure i can select which browser, window or profile i want to use for the authentication, i can now add the flag `--open-browser false` to get a link which can be copied to the browser or window the user selects.
=> feat: add flag to not open the browser automatically

internal/transformation/keepDescription.go, internal/transformation/keepDescription_test.go
This makes the kept description more readable if the source content is in html. 
thanks @frittentheke for bringing attention to this. 🙏🏼
fixes #176
=> fix: allow ugc content in keepDescription transformer

internal/adapter/outlook_http/client.go, internal/adapter/outlook_http/models.go
There were typos in the use of the use of the `EmailAddress` variable
=> fix: Fix typos (EmailAdress vs EmailAddress) in Outlook model and adapter

go.mod, go.sum, internal/adapter/google/client.go, internal/adapter/outlook_http/client.go
Making sure we're retrieving events in UTC and write them in the local timezone of the user.
=> fix: retrieve events always in UTC

internal/transformation/keepDescription.go
The policy can be reused, thus there's no need to recreate it for every processed calendar event.
Inspired by https://github.com/inovex/CalendarSync/issues/180 . But this barely changes the memory usage.
=> keepDescription: initialize bluemonday policy only once

cmd/calendarsync/main.go
Decrypting the credentials requires a lot of memory, such that later garbage collections only happen after doubling that memory usage again. Explicitly run a GC to reset the memory usage reference level.
Partial fix for https://github.com/inovex/CalendarSync/issues/180
=> Explicitly run garbage collection after loading credentials

internal/adapter/outlook_http/client.go
As the whole request body is read using io.ReadAll, thus the request can be freed immediately afterwards.
Might help with https://github.com/inovex/CalendarSync/issues/180 .
=> outlook: fix temporary memory leak while listing events

internal/adapter/google/adapter.go, internal/adapter/google/client.go, internal/adapter/outlook_http/adapter.go, internal/adapter/outlook_http/client.go, internal/adapter/sink_adapter.go, internal/adapter/source_adapter.go, internal/adapter/zep/client.go, internal/models/metadata.go, internal/sync/controller.go, internal/sync/controller_test.go, internal/sync/mocks/Sink.go, internal/sync/mocks/Source.go, internal/sync/synchronisation.go
When reading the code, I was confused about `GetCalendarID` function and the `calendarID` field, assuming they represent the same value. As this is not the case, and `GetCalendarID` returns a unique hash for a calendar, I renamed it to `GetCalendarHash`.
=> refactor: rename GetCalendarID to GetCalendarHash

cmd/calendarsync/main.go, internal/adapter/google/adapter.go, internal/adapter/outlook_http/adapter.go, internal/adapter/zep/client.go, internal/sync/controller.go
This PR changes the log messages to debug that are in my opinion not relevant to the users. I also added two info logs, one at the start and one at the end. Feel free to change some of the logs back to info if you think that they are helpful to the user. This PR closes #53.
=> Reduce logging

README.md, docs/adapters.md
Improve documentation on transformers, update google adapter documentation. The transformer documentation already includes #216.
=> Improve documentation

internal/adapter/google/client.go
Google Calendar API requires certain fields to be sent with a request, even though they might not be marshalled if they are set to their default, null or 0 - see [1]
This is the case e.g if an EventReminder has "0" minutes set which causes Google to reject with: `googleapi: Error 400: Missing override reminder minutes., required`
[1] https://pkg.go.dev/google.golang.org/api/calendar/v3?utm_source=godoc#EventReminder
=> fix(Google): force eventReminder overrides and their fields to always be sent
